name: Staging
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: amondnet/now-deployment@v2
        id: now-deployment
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.NOW_STAGING_ORG_ID }}
          now-project-id: ${{ secrets.NOW_STAGING_PROJECT_ID }}